import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Coursatty",
  description: "Generated by bo_0dy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="lg:w-[80%] w-full mx-auto bg-white rounded-lg my-3 overflow-hiddenw-[80%]">
        {children}
    </div>
  );
}
