import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from '@/redux/provider';
import { Nav } from "@/Components/Shared";
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coursatty",
  description: "Generated by bo_0dy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <Provider>
            <Nav />
            {children}
            <ToastContainer />
          </Provider>
        </body>
    </html>
  );
}
